config {
  schema: "staging",
  type: "incremental"
}
-- DELETE+INSERT
pre_operations {
  ${when(incremental(),
    `DELETE FROM ${self()} WHERE campagna_canvass IN (SELECT DISTINCT campagna_canvass FROM bli-bi-commerciale-test-001.landing.board_ft_consuntivo)`
  )}
}

SELECT
    *,
    CURRENT_TIMESTAMP() AS load_timestamp
FROM bli-bi-commerciale-test-001.landing.board_ft_consuntivo