config {
  schema: "staging",
  type: "incremental"
}
-- DELETE+INSERT
pre_operations {
  ${when(incremental(),
    `DELETE FROM ${self()} WHERE campagna_canvass_cd IN (SELECT DISTINCT campagna_canvass_cd FROM bli-bi-commerciale-prod-001.landing.board_consuntivo)`
  )}
}

SELECT
    *,
    CURRENT_TIMESTAMP() AS load_timestamp
FROM bli-bi-commerciale-prod-001.landing.board_consuntivo