config {
  schema: "staging",
  type: "incremental",
  protected: true,
  bigquery: {
    partitionBy: "mese",
    requirePartitionFilter : true
  }
}
-- DELETE+INSERT
pre_operations {
  ${when(incremental(),
    `DELETE FROM ${self()} WHERE mese IN (SELECT DISTINCT mese FROM bli-bi-commerciale-test-001.landing.board_budget)`
  )}
}

SELECT
    *,
    CURRENT_TIMESTAMP() AS load_timestamp
FROM bli-bi-commerciale-test-001.landing.board_budget